### ISSUE TITLE
does not compile under gccgo

### ISSUE THREAD

**Issue by rrh** [klauspost/crc32#11]
I installed gccgo (from gcc 5, on ubuntu).  The crc32_amd64.s source file doesn't compile, since that's cgo specific asm language:
  Godeps/_workspace/src/github.com/klauspost/crc32/crc32_amd64.s:9: Error: no such instruction: `text ·castagnoliSSE42(SB),NOSPLIT,$0'
....

There should be some kind of guard on the .s files (and/or the alternative pure go files) that detect when gccgo is in use and not compile the .s file(s).

**Comment by klauspost** [comment]
Thanks for the report.

Is it possible for you to test #12 ?

**Comment by rrh** [comment]
See my comment in #12 
I'd fix it myself, but the overhead of forking, changing this PR, is too high
Thanks for your very rapid response!

**Comment by klauspost** [comment]
Cheers
